/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
// By default, Docusaurus generates a sidebar from the docs folder structure
//tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'College Notes',
      link: {
        type: "doc",
        id: "college-notes/intro",
      },
      items: [
        {
          type: "category",
          label: "Year 12",
          link: {
            type: "doc",
            id: "college-notes/year-12/intro",
          },
          items: [
            {
              type: "category",
              label: "📙Unit 1",
              link: {
                type: "doc",
                id: "college-notes/year-12/unit-1/intro",
              },
              items: [
                "college-notes/year-12/unit-1/intro",
                "college-notes/year-12/unit-1/computational-thinking",
                "college-notes/year-12/unit-1/algorithm",
                "college-notes/year-12/unit-1/flowchart-and-pseudocode",
                {
                  type: "category",
                  label: "C#",
                  link: {
                    type: "doc",
                    id: "college-notes/year-12/unit-1/csharp/intro",
                  },
                  items: [
                    "college-notes/year-12/unit-1/csharp/intro",
                    "college-notes/year-12/unit-1/csharp/datatype",
                  ]
                },
              ],
            },
            {
              type: "category",
              label: "📘Unit 2",
              items: [
                "college-notes/year-12/unit-2/principle-of-computer",
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '🔒Year 13',
          link: {
            type: "doc",
            id: "college-notes/year-13/intro",
          },
          items: [
          ]
        },
      ],
    },
    {
      type: 'category',
      label: 'Personal Achievements in College',
      link: {
        type: "doc",
        id: "college-notes/personal-achievements/intro",
      },
      items: [
      ]
    },
  ],
  docs2: [
    {
      type: "category",
      label: "🔒University Notes",
      link: {
        type: "doc",
        id: "uni-notes/intro"
      },
      items: [
        "uni-notes/intro"
      ]
    },
  ],
};

module.exports = sidebars;
